version: '3.8'
services:
  shareit-gateway:
    build: gateway
    container_name: shareit_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  shareit-server:
    build: server
    container_name: shareit_server_container
    ports:
      - "9090:9090"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  postgresql:
    image: postgres:13.7-alpine
    container_name: postgresql_container
    ports:
      - "6541:5432"
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root