version: '3.8'
services:
  shareit-gateway:
    build: shareit-gateway
    container_name: shareit-gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SHAREIT_SERVER_URL=http://shareit-server:9090

  shareit-server:
    build: shareit-server
    container_name: shareit-server_container
    ports:
      - "9090:9090"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  postgresql:
    image: postgres:13.7-alpine
    restart: always
    container_name: postgresql_container
    ports:
      - "6541:5432"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root